### ISSUE TITLE
[Bug] Cannot create new world on 1.21

### ISSUE THREAD

**Issue by asimard1** [Stardust-Labs-MC/Nullscape#10]
### What Minecraft version(s) does this apply to?

1.20

### Project version

v1.2.6

### Mod or datapack version?

Datapack

### Describe the bug

When I go to create a new world, I simply get a crash. This also applies to the Amplified Nether mod. I am joining here the crash report:

[crash-2024-07-04_16.09.49-client.txt](https://github.com/user-attachments/files/16102579/crash-2024-07-04_16.09.49-client.txt)

**Comment by catter1** [comment]
Unsure. Can you confirm you downloaded the 1.21 version of Amplified Nether and Nullscape? They both use the same version number for their 1.20.x and 1.21 latest version. Screenshot of the Nullscape downloads, for example.

![image](https://github.com/Stardust-Labs-MC/Nullscape/assets/63272345/3a281dd1-c7c7-4cae-9af0-3fd4c487bd5a)

**Comment by asimard1** [comment]
I thought this was the case but now the problem is solved. Thank you :)
