### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Mandii511** [Stardust-Labs-MC/Nullscape#13]
### What Minecraft version(s) does this apply to?

1.21 - 1.21.1

### Project version

v1.2.8

### Mod or datapack version?

Fabric/Quilt Mod

### Describe the bug

I deleted the mod and now I can't go throught the End Portal. I didn't read the "Do now add to an existing end" Please Help!

**Comment by catter1** [comment]
Send your `level.dat` here

**Comment by catter1** [comment]
User asked in the discord, and it's a bit easier to communicate on there. Closing this issue.
