### ISSUE TITLE
[Bug] End Barrens and End Midlands biomes do not generate

### ISSUE THREAD

**Issue by hnrtrng** [Stardust-Labs-MC/Nullscape#5]
### What Minecraft version(s) does this apply to?

1.20

### Project version

v1.2.3

### Mod or datapack version?

Mod (Fabric)

### Describe the bug

The mod makes the Small End Islands biome and more dominantly the End Highlands biome the only vanilla biomes to generate in End's outer islands, while the End Barrens and End Midlands biomes are nowhere to be found (tested with /locate and Nature's Compass mod).

**Comment by catter1** [comment]
This was an intentional choice from Starmute
