### ISSUE TITLE
[Bug当

### ISSUE THREAD

**Issue by Qee1y** [Stardust-Labs-MC/Nullscape#6]
### What Minecraft version(s) does this apply to?

1.19.x

### Project version

Nullscape_1.19.3_v1.2.2

### Mod or datapack version?

Mod (Forge)

### Describe the bug

Hope to be compatible with enlightend, they will experience a world freeze。Due to the freeze, the game will not crash, resulting in no crash reports being generated

**Comment by catter1** [comment]
Does it crash without Enlightened? If the crash only occurs when **both** Enlightened and Nullscape are used, can you bring it up with them? Although I cannot tell for sure, Nullscape is likely not the cause, due to how it works. If it was the issue, crash logs would be produced.

**Comment by Qee1y** [comment]
> Does it crash without Enlightened? If the crash only occurs when **both** Enlightened and Nullscape are used, can you bring it up with them? Although I cannot tell for sure, Nullscape is likely not the cause, due to how it works. If it was the issue, crash logs would be produced.

Of course my testing isn't accurate, tested in a mod environment with only these two mods, no problems, and they don't cause crashes and such. Loading a map in End when these two mods are present in my modpack will easily cause the world to freeze. Remove one of these two and you won't experience the freezing issue.

**Comment by catter1** [comment]
Send your `latest.log` - not the crash log, but the normal log. My guess is that it's still an issue on Elightened's end, but it's worth taking a look.

**Comment by Qee1y** [comment]
I will send two different versions of logs, 1.20.1 and 1.19.2, which are strange. If there is a Nullscape in 1.19.2, there will be serious lag

**Comment by Qee1y** [comment]
1.19.2  [latest.log](https://github.com/Stardust-Labs-MC/Nullscape/files/13246886/latest.log)

Especially when entering the end, folding and jumping doors, or loading a large number of blocks at once, occasionally the world freezes

**Comment by catter1** [comment]
Your server is lagging - for what reason, I don't know. Not enough resurces dedicated to it? Another mod? But this is not a Nullscape-specific issue

**Comment by Qee1y** [comment]
Okay, maybe it's the lag caused by loading a large amount of resources? There are no bugs or other issues.

**Comment by catter1** [comment]
Large amount of resources, not enough RAM, too many functions or players... could be any of them. Also, if you have not pregenerated your end, I'd recommend that (check out Chunky). That will help get rid of a lot of world generation lag.
