### ISSUE TITLE
[Bug] End Gateways do not spawn, thus requiring users to manually travel thousands of blocks to return to the main end island.

### ISSUE THREAD

**Issue by MagmaSlime123** [Stardust-Labs-MC/Nullscape#7]
### What Minecraft version(s) does this apply to?

1.20

### Project version

1.2.3.

### Mod or datapack version?

Datapack

### Describe the bug

Title.

### Additional context

N/A.

**Comment by catter1** [comment]
I was not able to replicate your issue. Can you try again, and make sure you don't have any other mods or datapacks installed? If it continues to be an issue, please provide as much detail as you can about your game (datapacks, mods, existing world, logs, etc)

![2023-12-14_00 01 02](https://github.com/Stardust-Labs-MC/Nullscape/assets/63272345/8f3e8c8f-544a-445f-8110-417b2409449e)

**Comment by MagmaSlime123** [comment]
This is on a Paper server with a few plugins on 1.20.1, I imported this world from Singleplayer with the datapacks already loaded.

**Comment by catter1** [comment]
Were you able to replicate the issue without any plugins on a fresh world?

**Comment by MagmaSlime123** [comment]
Yep.

**Comment by catter1** [comment]
Apologies for the delay in response, as I have been completely unavailable the past couple of days.

Could you send the `level.dat` from your `world` folder? This makes no sense that you are having this issue, on a COMPLETELY new world with nothing except Nullscape installed.

**Comment by MagmaSlime123** [comment]
.dat files are not supported on GitHub.

https://www.dropbox.com/scl/fi/llw9h9jbbg2vcs3wr82ym/level.dat?rlkey=esr19t7a1cz5sl6t1260hped3&dl=0

**Comment by catter1** [comment]
I'm sorry, I guess I completely missed the reply... 5 months ago. Reopen the issue if you still need help.
